language: ruby
cache: bundler
rvm:
  - 2.5.3

install:
  # Install Jekyll and dependencies
  - bundle install

script: bundle exec rake site

branches:
  only:
  - master

notifications:
  email: false