# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Umut D. | Kişisel Web Sitesi
email: batu2k@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Bolca programlama, kod ve video eğitim içeren bir teknoloji sitesi. Sade, temiz, minimalist, açık kaynak kodlu ve reklamsız.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.umutd.com" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:categories/:title

# Plainwite ayarları
plainwhite:
  name: Umut D.
  tagline: Programmer, Developer
  date_format: "%b %-d. %Y"
  analytics_id: 'UA-39578410-1'
  sitemap: true
  show_excerpts: true

  social_links:
    stack_overflow: umut-d
    github:  umut-d
    youtube: umutdokel

# Build settings
markdown: kramdown
theme: plainwhite
plugins:

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/